// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAknSNK50BY1-D-FyIwklsQ6W_hkIXqqXk',
    appId: '1:419842971837:web:4d1819986633a4e0e8ffd4',
    messagingSenderId: '419842971837',
    projectId: 'project-firebase-bfd00',
    authDomain: 'project-firebase-bfd00.firebaseapp.com',
    databaseURL: 'https://project-firebase-bfd00-default-rtdb.firebaseio.com/',
    storageBucket: 'project-firebase-bfd00.appspot.com',
    measurementId: 'G-XXQ7S50N8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWfrTndTjGTc0YzRGDGMvufzSISr0msDA',
    appId: '1:419842971837:android:5415aad364bf8113e8ffd4',
    messagingSenderId: '419842971837',
    projectId: 'project-firebase-bfd00',
    storageBucket: 'project-firebase-bfd00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbL0biW1Wevp5HKkJKs0lI_1OPbUJ6L9Q',
    appId: '1:419842971837:ios:1918cb6f8a258b20e8ffd4',
    messagingSenderId: '419842971837',
    projectId: 'project-firebase-bfd00',
    storageBucket: 'project-firebase-bfd00.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbL0biW1Wevp5HKkJKs0lI_1OPbUJ6L9Q',
    appId: '1:419842971837:ios:3920b7aae7490dc3e8ffd4',
    messagingSenderId: '419842971837',
    projectId: 'project-firebase-bfd00',
    storageBucket: 'project-firebase-bfd00.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
